services:
  server:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
  postgres:
    image: postgres:12
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - .env
  prisma:
    image: node:lts
    working_dir: /app
    command: sh -c "npx prisma db push --accept-data-loss --skip-generate"
    depends_on:
      - "postgres"
    volumes:
      - ./api/prisma:/app/prisma
    env_file:
      - .env
  api:
    build: ./api
    command: npx nodemon src/index.ts
    restart: always
    depends_on:
      - "postgres"
      - "prisma"
    ports:
      - "4000:4000"
    volumes:
      - ./api/src:/usr/src/app/src
    env_file:
      - .env
